### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by upamaru0104** [upamaru0104/protospace-39197#4]
(https://protospace-39197.onrender.com)

**Comment by shodai-ito** [comment]
@upamaru0104 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
空のコメントを投稿すると、ページに留まらずエラー画面になってしまいます。

- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
コメント投稿者名をクリックすると、プロトタイプ投稿者の詳細ページに遷移してしまいます。

- [x] **ログアウト状態のユーザーであっても、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページには遷移できること**
ログアウト状態でプロトタイプ詳細ページに遷移できませんでした。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by upamaru0104** [comment]
修正しました

**Comment by shodai-ito** [comment]
@upamaru0104 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

※ログイン前とログイン後のトップページのレイアウトを揃えると、よりユーザー体験がよくなるかと思われます。
こちらは必須ではないため、修正の報告は不要です。

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
